# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfb5587021d770cbab20b5a75ace900830535c05912f3c87e6e96255c5dc5e3aa9abf8f4efa8eee3708a46bfed5025721f37ac025298a5eaedf780ef7a4637e3

test:
  secret_key_base: 9a36d62b950d32909fafd33d9e4723698e4b3d22adac38eb792fe2a93e7cbe68d19cc1a99845ded6423128235c1475d78c597a77b25c23103fc6cd407a8999a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
